<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>ck</ToolCommandName>
    <PackageId>ContextKit</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContextKit.Hosting\ContextKit.Hosting.csproj" />
    <ProjectReference Include="..\ContextKit.Registry\ContextKit.Registry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
