<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <PackageId>ContextKit.Mcp.Adapter</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContextKit.Core\ContextKit.Core.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>

</Project>
