<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <Using Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ContextKit.Cli\ContextKit.Cli.csproj" />
    <ProjectReference Include="..\..\src\ContextKit.Mcp\ContextKit.Mcp.csproj" />
  </ItemGroup>

</Project>